---
- name: "Download tomcat {{ tomcat_version }}"
  get_url:
     url: "http://{{ mirror_host }}/apache/tomcat/tomcat-8/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
     dest: "{{ target_dir }}"
     checksum: sha1:eaf69c8c8802e574447baa2d38472e80e5f81d78
  register: get_tomcat
     

- debug:
      msg: "System {{ inventory_hostname }} download  tomcat  {{ tomcat_version }} on server"
  when: get_tomcat|changed


- name: "Untar apache-tomcat-{{ tomcat_version }}"
  unarchive :
      src: "{{ target_dir}}/apache-tomcat-{{ tomcat_version }}.tar.gz"
      dest: "{{ target_dir }}"
      remote_src: yes 
     

- debug:
      msg: "System {{ inventory_hostname }} untar tomcat {{ tomcat_version }}"
