---
- name: Wait for roller deployed
  wait_for: 
      path: "{{ roller_root }}/WEB-INF/classes/"

- debug:
    msg: "deploy roller.war to roller wait"

- name: roller roller-custom.properties copied into WEB-INF/classes/
  template:
      src: "templates/roller-custom.properties.j2" 
      dest: "{{ roller_root }}/WEB-INF/classes/{{ roller_property }}"
- debug:
    msg: "copy  roller-custom.properties to {{ roller_root }}/WEB-INF/classes directory"
